export default {
  FETCH_PROBLEMS: 'FETCH_PROBLEMS',
  FETCH_PROBLEMS_SUCCESS: 'FETCH_PROBLEMS_SUCCESS',
  SELECT_PROBLEM: 'SELECT_PROBLEM',
  UPDATE_PROBLEM: 'UPDATE_PROBLEM',
  UPDATE_PROBLEM_SUCCESS: 'UPDATE_PROBLEM_SUCCESS',
};