const PROBLEM_STATUS = {
    ATTEMPTED: 'ATTEMPTED',
    SOLVED: 'SOLVED',
};

const PROBLEM_DIFFICULTY = {
    EASY: 'EASY',
    MEDIUM: 'MEDIUM',
    HARD: 'HARD',
};

module.exports = {
    PROBLEM_STATUS,
    PROBLEM_DIFFICULTY
}