const PREFIX = 'AUTH_';

const ActionTypes = {
  INIT: `${PREFIX}INIT`,
  SIGN_UP: `${PREFIX}SIGN_UP`,
  SIGN_UP_SUCCESS: `${PREFIX}_SIGN_UP_SUCCESS`,
  SIGN_UP_FAIL: `${PREFIX}SIGN_UP_FAIL`,
  LOG_IN: `${PREFIX}LOG_IN`,
  LOG_IN_SUCCESS: `${PREFIX}_LOG_IN_SUCCESS`,
  LOG_IN_FAIL: `${PREFIX}LOG_IN_FAIL`,
  LOG_OUT: `${PREFIX}LOG_OUT`,
  LOG_OUT_SUCCESS: `${PREFIX}_LOG_OUT_SUCCESS`,
};

export default ActionTypes;
