export default {
  INIT: 'PROBLEMS_INIT',
  FETCH_PROBLEMS: 'FETCH_PROBLEMS',
  FETCH_PROBLEMS_SUCCESS: 'FETCH_PROBLEMS_SUCCESS',
  SELECT_PROBLEM: 'SELECT_PROBLEM',
  UPDATE_PROBLEM: 'UPDATE_PROBLEM',
  ADD_PROBLEM: 'ADD_PROBLEM',
  UPDATE_PROBLEM_INPUT: 'UPDATE_PROBLEM_INPUT',
};